name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    name: self-hosted - Python 3.10
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10"]
        build: ['']
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Install
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install -e .

    - name: Display Python version
      run: |
        python -VV
        python -c 'import sysconfig; print("Free threading?", "Yes" if sysconfig.get_config_var("Py_GIL_DISABLED") else "No")'

    - name: Checkout EcOps action
      uses: actions/checkout@v4
      with:
        repository: CarlosPHN/EcOps
        token: ${{TOKEN}}
        path: ecops-action

    - name: Start EcOps Measurement
      if: always()
      uses: ./ecops-action
      with:
        method: start_measurement
        args: perf power/energy-cores/ power/energy-pkg/ 50

    - name: Run Tests
      id: pyperformance
      run: python -u -m pyperformance.tests

    - name: End EcOps Measurement
      if: always()
      uses: ./ecops-action
      with:
        method: end_measurement
