name: Tests

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
    - name: Set up Python 3.11
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
      with:
        python-version: 3.11
        cache: 'pip'
        allow-prereleases: true
    - name: Install dependencies
      run: |
        make
    - name: Run tests
      run: |
        make ci
