name: Test

on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
        cache: pip
        cache-dependency-path: tox.ini

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox

    - name: Checkout EcOps action
      uses: actions/checkout@v4
      with:
        repository: CarlosPHN/EcOps
        token: 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
        path: ecops-action

    - name: Start EcOps Measurement
      uses: ./ecops-action
      with:
        method: start_measurement
        args: perf power/energy-cores/ power/energy-pkg/ 50

    - name: Tests
      run: |
          tox -e py

    - name: End EcOps Measurement
      if: always()
      uses: ./ecops-action
      with:
        method: end_measurement

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        name: Python ${{ matrix.python-version }}