name: Test

on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        allow-prereleases: true
        cache: pip
        cache-dependency-path: tox.ini

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox

    - name: Checkout EcOps action
      uses: actions/checkout@v4
      with:
        repository: CarlosPHN/EcOps
        token: ${{TOKEN}}
        path: ecops-action

    - name: Start EcOps Measurement
      if: always()
      uses: ./ecops-action
      with:
        method: start_measurement
        args: perf power/energy-cores/ power/energy-pkg/ 50

    - name: Tests
      run: tox -e py

    - name: End EcOps Measurement
      if: always()
      uses: ./ecops-action
      with:
        method: end_measurement

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        name: Python 3.11
