name: CI

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    permissions:
      actions: write
      contents: read
    name: "pom.xml on JDK 21 on self-hosted"
    runs-on: self-hosted
    env:
      ROOT_POM: pom.xml
    steps:
      - name: 'Cancel previous runs'
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa
        with:
          access_token: ${{ github.token }}

      - name: 'Check out repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: 'Set up JDK 21'
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: 'Install'
        shell: bash
        run: ./mvnw -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dtoolchain.skip install -U -DskipTests=true -f $ROOT_POM

      - name: 'Test'
        shell: bash
        run: ./mvnw -B -P!standard-with-extra-repos -Dtoolchain.skip verify -U -Dmaven.javadoc.skip=true -Dsurefire.toolchain.version=21 -f $ROOT_POM

      - name: 'Print Surefire reports'
        if: ${{ failure() }}
        shell: bash
        run: ./util/print_surefire_reports.sh

      - name: 'Set up Gradle'
        uses: gradle/actions/setup-gradle@v4

      - name: 'Integration Test'
        shell: bash
        run: util/gradle_integration_tests.sh
