name: CI

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    permissions:
      actions: write
      contents: read
    name: "pom.xml on JDK 21 on self-hosted"
    runs-on: self-hosted
    env:
      ROOT_POM: pom.xml
    steps:
      - name: 'Cancel previous runs'
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa
        with:
          access_token: ${{ github.token }}

      - name: 'Check out repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: 'Set up JDKs 21 and 24'
        uses: actions/setup-java@v4
        with:
          java-version: |
            21
            24
          distribution: temurin
          cache: maven

      - name: 'Install'
        shell: bash
        run: ./mvnw -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dtoolchain.skip install -U -DskipTests=true -f $ROOT_POM

      - name: Checkout EcOps action
        uses: actions/checkout@v4
        with:
          repository: CarlosPHN/EcOps
          token: ${{TOKEN}}
          path: ecops-action

      - name: Start EcOps Measurement
        if: always()
        uses: ./ecops-action
        with:
          method: start_measurement
          args: perf power/energy-cores/ power/energy-pkg/ 50

      - name: 'Test'
        shell: bash
        run: ./mvnw -B -P!standard-with-extra-repos -Dtoolchain.skip verify -U -Dmaven.javadoc.skip=true -Dsurefire.toolchain.version=21 -f $ROOT_POM

      - name: End EcOps Measurement
        if: always()
        uses: ./ecops-action
        with:
          method: end_measurement

      - name: 'Print Surefire reports'
        if: ${{ failure() }}
        shell: bash
        run: ./util/print_surefire_reports.sh